"use client";

import { motion } from "framer-motion";
import { Check, CheckCheck, TrendingUp, Users, Wallet } from "lucide-react";
import { Reveal } from "@/components/site/reveal";

function WhatsAppMock() {
  const messages = [
    { from: "bot", text: "Hi Ahmed! 👋 Your Gold membership renews in 3 days. Want me to send the payment link?", time: "9:41" },
    { from: "user", text: "Yes please", time: "9:42" },
    { from: "bot", text: "Done ✅ Here you go — tap to pay by card or wallet. See you at leg day! 💪", time: "9:42" },
  ];
  return (
    <div className="mx-auto w-full max-w-sm overflow-hidden rounded-2xl border border-border bg-[#0b141a] shadow-2xl">
      <div className="flex items-center gap-3 bg-[#202c33] px-4 py-3">
        <div className="flex h-9 w-9 items-center justify-center rounded-full bg-primary text-sm font-bold text-primary-foreground">GP</div>
        <div>
          <div className="text-sm font-medium text-white">GymPilot Assistant</div>
          <div className="text-xs text-emerald-400">online</div>
        </div>
      </div>
      <div className="space-y-2 px-3 py-4">
        {messages.map((m, i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 8 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.25 }}
            className={m.from === "user" ? "flex justify-end" : "flex justify-start"}
          >
            <div
              className={`max-w-[80%] rounded-lg px-3 py-2 text-sm ${
                m.from === "user" ? "bg-[#005c4b] text-white" : "bg-[#202c33] text-white"
              }`}
            >
              {m.text}
              <span className="ml-2 inline-flex items-center gap-0.5 text-[10px] text-white/50">
                {m.time}
                {m.from === "user" ? <CheckCheck className="h-3 w-3 text-sky-400" /> : <Check className="h-3 w-3" />}
              </span>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function DashboardMock() {
  const stats = [
    { icon: Users, label: "Active members", value: "412", trend: "+18" },
    { icon: Wallet, label: "Collected (Jul)", value: "$12.4k", trend: "+9%" },
    { icon: TrendingUp, label: "Renewal rate", value: "87%", trend: "+5%" },
  ];
  const bars = [40, 62, 48, 75, 68, 90, 82];
  return (
    <div className="w-full rounded-2xl border border-border bg-card p-5 shadow-2xl">
      <div className="mb-4 flex items-center justify-between">
        <div>
          <div className="text-sm font-semibold">This month at a glance</div>
          <div className="text-xs text-muted-foreground">Auto-generated by GymPilot AI</div>
        </div>
        <span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Live</span>
      </div>
      <div className="grid grid-cols-3 gap-3">
        {stats.map((s) => (
          <div key={s.label} className="rounded-lg border border-border bg-background/50 p-3">
            <s.icon className="h-4 w-4 text-primary" />
            <div className="mt-2 text-lg font-bold leading-none">{s.value}</div>
            <div className="mt-1 text-[11px] text-muted-foreground">{s.label}</div>
            <div className="mt-1 text-[11px] font-medium text-emerald-500">{s.trend}</div>
          </div>
        ))}
      </div>
      <div className="mt-4 flex h-28 items-end gap-2 rounded-lg border border-border bg-background/50 p-3">
        {bars.map((h, i) => (
          <motion.div
            key={i}
            initial={{ height: 0 }}
            whileInView={{ height: `${h}%` }}
            viewport={{ once: true }}
            transition={{ delay: i * 0.06, duration: 0.5 }}
            className="flex-1 rounded-t bg-gradient-to-t from-primary/40 to-primary"
          />
        ))}
      </div>
    </div>
  );
}

export function Mockups() {
  return (
    <section id="mockups" className="border-t border-border/60 py-24">
      <div className="container">
        <Reveal className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold uppercase tracking-wider text-primary">A peek at the product</p>
          <h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">
            Your gym, running while you sleep
          </h2>
          <p className="mt-4 text-muted-foreground">
            This is the direction we&apos;re building. Your survey answers decide what we ship first.
          </p>
        </Reveal>

        <div className="mt-16 grid items-center gap-8 lg:grid-cols-2">
          <Reveal>
            <div className="rounded-2xl border border-border bg-gradient-to-b from-secondary/40 to-transparent p-8">
              <WhatsAppMock />
            </div>
            <p className="mt-4 text-center text-sm text-muted-foreground">
              Members chat on WhatsApp. The AI handles renewals, bookings and questions.
            </p>
          </Reveal>
          <Reveal delay={0.1}>
            <div className="rounded-2xl border border-border bg-gradient-to-b from-secondary/40 to-transparent p-8">
              <DashboardMock />
            </div>
            <p className="mt-4 text-center text-sm text-muted-foreground">
              One dashboard shows revenue, active members and what needs attention.
            </p>
          </Reveal>
        </div>
      </div>
    </section>
  );
}
